steps:
# build the binaries
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'hello', 'src/main.go']

# Ensure that "go get" works
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['get', 'golang.org/x/net/context']
  env: ['GOPATH=/tmp']



# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
      '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA', 
       '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
       '-f', 'Dockerfile', '.']

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'